### ISSUE TITLE
Deploying on Docker? 

### ISSUE THREAD

**Issue by timrettop** [BjoernKW/MailTrigger#1]
Hello, 

Have you considered implementing docker build options and docker hub or other publishing to be able to easily deploy this in a docker container?

**Comment by BjoernKW** [comment]
So far, I haven't actively pursued this, but a Docker build option or an image on Docker Hub most definitely is a good idea.

**Comment by BjoernKW** [comment]
@timrettop It took me a bit of time but there now is a [MailTrigger Docker image](https://hub.docker.com/repository/docker/bjoernkw/mailtrigger)!

As an added benefit, MailTrigger now also allows you to configure a custom template directory.

**Comment by BjoernKW** [comment]
This is the public URL for the [MailTrigger Docker image](https://hub.docker.com/r/bjoernkw/mailtrigger): https://hub.docker.com/r/bjoernkw/mailtrigger
